[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.10142770.svg)](https://doi.org/10.5281/zenodo.10142770)
# [**SQLxMatch: In-Database Spatial Cross-Match of Astronomical Catalogs**](https://github.com/sciserver/SQLxMatch)

In [12]:
from SciServer import CasJobs as cj
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 20)

from SciServer import Authentication
Authentication.login(UserName = "Alberto_2002", Password = "#Blackie2002")

'b29fa67cf5ca45f9ba48bf69850c7f51'

In [13]:
sql = "SELECT TOP 100 ra,dec FROM specObj WHERE ra BETWEEN 140.25 and 140.75 AND dec BETWEEN 20.25 and 20.75"
cj.executeQuery(sql, context='DR18')

           ra        dec
0   140.25261  20.610689
1   140.25335  20.430728
2   140.26132  20.376150
3   140.26652  20.274860
4   140.26679  20.410276
..        ...        ...
95  140.60178  20.658604
96  140.60852  20.330740
97  140.61145  20.350790
98  140.61387  20.460046
99  140.61532  20.355910

[100 rows x 2 columns]

In [14]:
sql = "SELECT ra,dec FROM specObj WHERE ra BETWEEN 140.25 and 140.75 AND dec BETWEEN 20.25 and 20.75 AND class='GALAXY'"
cj.executeQuery(sql, context='DR18')

           ra        dec
0   140.25335  20.430728
1   140.26652  20.274860
2   140.26679  20.410276
3   140.26903  20.736134
4   140.26998  20.665789
..        ...        ...
83  140.73026  20.441962
84  140.74094  20.320367
85  140.74187  20.343130
86  140.74730  20.292745
87  140.74828  20.343699

[88 rows x 2 columns]

In [15]:
sql = "SELECT obj,ra,dec,u,g,r,i,z FROM galaxy WHERE ra BETWEEN 140.9 and 141.1 AND g < 18.0 AND (u-g) > 2.2"
cj.executeQuery(sql, context='DR18')

,obj,ra,dec,u,g,r,i,z
0,436,140.950378,2.109527,20.74449,17.78611,17.62807,16.944470,27.22122
1,47,141.027609,3.464546,24.63467,16.24791,16.01205,15.619690,22.83003
2,112,140.951380,-2.091327,25.92446,16.30754,16.97829,15.755040,24.33615
3,106,141.030856,35.519360,22.28843,15.77590,15.06693,14.045040,19.88577
4,89,141.030462,30.060275,13.77203,10.65002,10.08757,9.867542,10.47052
...,...,...,...,...,...,...,...,...
275,40,141.018916,64.036931,15.07759,11.61257,11.12426,11.053250,11.58111
276,20,140.947090,64.878411,14.13258,11.86711,11.29087,11.212120,13.22313
277,37,141.097408,25.784674,18.02059,15.53275,14.07274,13.289560,12.06627
278,41,140.947329,17.651562,21.12601,16.08016,15.70101,14.888890,15.96704
279,77,140.946492,17.646839,24.00525,17.50282,16.33996,15.351740,25.02391

In [16]:
sql = "SELECT bestObjID, ra, dec, z FROM specObj WHERE class='qso' AND z > 4.5 AND zWarning = 0"
cj.executeQuery(sql, context='DR18')

                bestObjID          ra        dec         z
0     1237655465388999582  226.877660  55.619792  4.500312
1     1237678618504397427   29.345420   2.044303  4.501918
2     1237674650996769779  167.109670   0.618528  4.503146
3     1237674460417754011  145.020010   5.441946  4.503848
4     1237666407920829375   34.927581  -0.193602  4.504642
...                   ...         ...        ...       ...
3131  1237661434309837083  189.847870  47.317133  7.028330
3132                    0   86.158514  -8.397181  7.029691
3133  1237659329236566645  235.278200  47.039639  7.032396
3134  1237662302439080247  227.172790  44.374119  7.040438
3135  1237668591340290733  200.996950  17.910995  7.042325

[3136 rows x 4 columns]

In [17]:
sql = "SELECT p.ObjID, p.ra, p.dec, p.u, p.g, p.r, p.i, p.z FROM photoObj p JOIN dbo.fGetNearbyObjEq(140,20,5) n ON n.objID = p.objID WHERE p.type = 3"
cj.executeQuery(sql, context='DR18')

,ObjID,ra,dec,u,g,r,i,z
0,1237667292652896786,139.965784,19.953361,24.00691,22.68134,21.72697,21.46717,21.19963
1,1237667292652896808,139.978215,19.950970,22.20080,22.29743,21.78929,22.82182,22.02206
2,1237667292652896816,139.985532,19.945355,22.94799,22.46340,21.55696,21.51550,20.71875
3,1237667292652896747,139.941605,19.949516,23.31602,22.81213,22.16026,22.60339,21.44061
4,1237667292652896587,139.976721,19.929997,20.57198,19.58015,19.08220,18.86908,18.79610
...,...,...,...,...,...,...,...,...
246,1237667430093488659,139.992003,20.039046,21.73288,20.85391,20.08521,19.55354,19.47026
247,1237667430093488675,140.006261,20.033522,23.27886,22.92345,22.28987,21.99580,22.17885
248,1237667430093488937,140.001410,20.032974,22.49799,23.96643,21.05082,20.15596,19.12539
249,1237667430093488945,140.011122,20.028503,20.82170,21.68647,20.37486,19.87578,19.10124
250,1237667430093488936,140.002453,20.023265,25.63818,23.24328,21.91645,21.58004,20.86370

In [18]:
sql = f"""
SELECT TOP 10
   p.objid,
   p.ra,
   p.dec,
   p.run,
   p.rerun,
   p.camcol,
   p.field,
   s.z AS redshift
FROM PhotoObj AS p
JOIN SpecObj AS s ON s.bestobjid = p.objid
WHERE s.class = 'QSO'
"""
cj.executeQuery(sql, context='DR18')

,objid,ra,dec,run,rerun,camcol,field,redshift
0,1237679580008547213,23.631319,30.353151,7941,301,2,42,0.000461
1,1237658203433271409,169.544951,48.036748,2964,301,1,253,0.000461
2,1237657628981133592,146.923715,45.404365,2830,301,3,249,0.000632
3,1237663783140131202,37.692814,-0.758683,4263,301,2,367,0.000956
4,1237664293686542588,204.568544,37.277746,4382,301,1,95,0.000957
5,1237665567150309961,229.825548,19.102298,4678,301,5,186,0.001040
6,1237661872407642175,198.034161,44.014780,3818,301,3,231,0.001126
7,1237678806386147950,28.184407,31.761413,7761,301,1,173,0.001669
8,1237662223523053590,163.171905,36.669169,3900,301,1,259,0.001836
9,1237661360762651083,206.828658,44.612196,3699,301,2,124,0.008691

In [19]:
sql = f"""
SELECT TOP 10
   f.img
FROM Frame AS f
"""
cj.executeQuery(sql, context='DR18')

                                                 img
0  0x0000000c6a5020200d0a870a00000014667479706a70...
1  0x0000000c6a5020200d0a870a00000014667479706a70...
2  0x0000000c6a5020200d0a870a00000014667479706a70...
3  0x0000000c6a5020200d0a870a00000014667479706a70...
4  0x0000000c6a5020200d0a870a00000014667479706a70...
5  0x0000000c6a5020200d0a870a00000014667479706a70...
6  0x0000000c6a5020200d0a870a00000014667479706a70...
7  0x0000000c6a5020200d0a870a00000014667479706a70...
8  0x0000000c6a5020200d0a870a00000014667479706a70...
9  0x0000000c6a5020200d0a870a00000014667479706a70...

In [20]:
sql = """
SELECT TOP 10
   p.objid,
   p.ra,
   p.dec,
   p.run,
   p.rerun,
   p.camcol,
   p.field,
   s.z AS redshift
FROM PhotoObj AS p
JOIN SpecObj AS s ON s.bestobjid = p.objid
WHERE s.class = 'QSO'
"""
results = cj.executeQuery(sql, context='DR18')